# Tideland Common Go Library - Simple Markup Language
#
# Copyright 2009-2011 Frank Mueller / Oldenburg / Germany. 
#
# All rights reserved. Use of this source code is 
# governed by a BSD-style license that can be found
# in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/tcgl/markup

GOFILES=\
	markup.go\

include $(GOROOT)/src/Make.pkg

#
# EOF
#
