# Tideland Common Go Library - Finite State Machine
#
# Copyright 2009-2011 Frank Mueller / Oldenburg / Germany. 
#
# All rights reserved. Use of this source code is 
# governed by a BSD-style license that can be found
# in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/tcgl/state

GOFILES=\
	state.go\
	doc.go\

include $(GOROOT)/src/Make.pkg

#
# EOF
#
